/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DocumentEventListener: typeof import('@solid-primitives/event-listener').DocumentEventListener
  const Dynamic: typeof import('solid-js/web').Dynamic
  const ErrorBoundary: typeof import('solid-js').ErrorBoundary
  const For: typeof import('solid-js').For
  const Index: typeof import('solid-js').Index
  const Match: typeof import('solid-js').Match
  const OInput: typeof import('../src/components/input/index')['OInput']
  const OMarkdown: typeof import('../src/components/markdown/index')['OMarkdown']
  const OModal: typeof import('../src/components/modal/index').OModal
  const OPopup: typeof import('../src/components/popup/index').OPopup
  const OSplit: typeof import('../src/components/split/index').OSplit
  const OSplitItem: typeof import('../src/components/split/index').OSplitItem
  const OToast: typeof import('../src/components/toast/index').OToast
  const Portal: typeof import('solid-js/web').Portal
  const Show: typeof import('solid-js').Show
  const Suspense: typeof import('solid-js').Suspense
  const SuspenseList: typeof import('solid-js').SuspenseList
  const Switch: typeof import('solid-js').Switch
  const Teleport: typeof import('../src/components/teleport/index').Teleport
  const Transition: typeof import('solid-transition-group').Transition
  const TransitionGroup: typeof import('solid-transition-group').TransitionGroup
  const WindowEventListener: typeof import('@solid-primitives/event-listener').WindowEventListener
  const batch: typeof import('solid-js').batch
  const button: typeof import('../src/directives/index').button
  const children: typeof import('solid-js').children
  const createContext: typeof import('solid-js').createContext
  const createDeferred: typeof import('solid-js').createDeferred
  const createEffect: typeof import('solid-js').createEffect
  const createEventListener: typeof import('@solid-primitives/event-listener').createEventListener
  const createEventListenerMap: typeof import('@solid-primitives/event-listener').createEventListenerMap
  const createEventSignal: typeof import('@solid-primitives/event-listener').createEventSignal
  const createMemo: typeof import('solid-js').createMemo
  const createMousePosition: typeof import('@solid-primitives/mouse').createMousePosition
  const createMutable: typeof import('solid-js/store').createMutable
  const createPositionToElement: typeof import('@solid-primitives/mouse').createPositionToElement
  const createRenderEffect: typeof import('solid-js').createRenderEffect
  const createResource: typeof import('solid-js').createResource
  const createRoot: typeof import('solid-js').createRoot
  const createSelector: typeof import('solid-js').createSelector
  const createSignal: typeof import('solid-js').createSignal
  const createStore: typeof import('solid-js/store').createStore
  const debounce: typeof import('../src/directives/index').debounce
  const draggable: typeof import('../src/directives/index').draggable
  const getOwner: typeof import('solid-js').getOwner
  const getPositionInElement: typeof import('@solid-primitives/mouse').getPositionInElement
  const getPositionToElement: typeof import('@solid-primitives/mouse').getPositionToElement
  const getPositionToScreen: typeof import('@solid-primitives/mouse').getPositionToScreen
  const hydrate: typeof import('solid-js/web').hydrate
  const indexArray: typeof import('solid-js').indexArray
  const insert: typeof import('solid-js/web').insert
  const isServer: typeof import('solid-js/web').isServer
  const lazy: typeof import('solid-js').lazy
  const longpress: typeof import('../src/directives/index').longpress
  const makeEventListener: typeof import('@solid-primitives/event-listener').makeEventListener
  const makeEventListenerStack: typeof import('@solid-primitives/event-listener').makeEventListenerStack
  const makeMouseInsideListener: typeof import('@solid-primitives/mouse').makeMouseInsideListener
  const makeMousePositionListener: typeof import('@solid-primitives/mouse').makeMousePositionListener
  const mapArray: typeof import('solid-js').mapArray
  const mergeProps: typeof import('solid-js').mergeProps
  const noop: typeof import('../src/utils/index').noop
  const observable: typeof import('solid-js').observable
  const on: typeof import('solid-js').on
  const onCleanup: typeof import('solid-js').onCleanup
  const onError: typeof import('solid-js').onError
  const onMount: typeof import('solid-js').onMount
  const preventDefault: typeof import('@solid-primitives/event-listener').preventDefault
  const produce: typeof import('solid-js/store').produce
  const reconcile: typeof import('solid-js/store').reconcile
  const render: typeof import('solid-js/web').render
  const renderToStream: typeof import('solid-js/web').renderToStream
  const renderToString: typeof import('solid-js/web').renderToString
  const renderToStringAsync: typeof import('solid-js/web').renderToStringAsync
  const runWithOwner: typeof import('solid-js').runWithOwner
  const splitProps: typeof import('solid-js').splitProps
  const stop: typeof import('../src/directives/index').stop
  const stopImmediatePropagation: typeof import('@solid-primitives/event-listener').stopImmediatePropagation
  const stopPropagation: typeof import('@solid-primitives/event-listener').stopPropagation
  const toastActions: typeof import('../src/components/toast/index').toastActions
  const untrack: typeof import('solid-js').untrack
  const useContext: typeof import('solid-js').useContext
  const useLastPointerDown: typeof import('../src/utils/index').useLastPointerDown
  const useMousePosition: typeof import('@solid-primitives/mouse').useMousePosition
  const useTransition: typeof import('solid-js').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { JSX, Accessor, Setter, Component } from 'solid-js'
  import('solid-js')
}
